name: hourly-refresh
on:
  schedule:
    - cron: '@hourly'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://twitter-diary.herokuapp.com/refresh'
